# Generated by Django 2.1.2 on 2018-11-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reniec', models.CharField(blank=True, max_length=6)),
                ('inei', models.CharField(blank=True, max_length=6)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'proxy': True,
                'indexes': [],
            },
            bases=('ubigeo.ubigeo',),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ubigeo.ubigeo',),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ubigeo.ubigeo',),
        ),
    ]
