# Generated by Django 2.1.2 on 2018-11-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('genero', models.IntegerField(choices=[(0, 'MASCULINO'), (1, 'FEMENINO')])),
                ('estado_civil', models.IntegerField(choices=[(0, 'SOLTERO'), (1, 'CASADO'), (2, 'VIUDO'), (3, 'DIVORCIADO')])),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=30)),
                ('celular', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Policia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.IntegerField(choices=[(0, 'MAYOR'), (1, 'CORONEL'), (2, 'OTRO'), (3, 'OTROS')], max_length=20)),
                ('descripcion_funciones', models.CharField(max_length=100)),
                ('polica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.Persona')),
            ],
            options={
                'verbose_name': 'Policia',
                'verbose_name_plural': 'Policias',
            },
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_academico', models.IntegerField(choices=[(0, 'Doctor'), (1, 'Ingeniero'), (2, 'Empresario'), (3, 'Emprendedor')], max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.Persona')),
            ],
            options={
                'verbose_name': 'Turista',
                'verbose_name_plural': 'Turistas',
            },
        ),
    ]
