# Generated by Django 2.1.2 on 2018-11-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acontecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Acontecimiento',
                'verbose_name_plural': 'Acontecimientos',
            },
        ),
        migrations.CreateModel(
            name='Hecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_acontecimiento', models.DateField()),
                ('fecha_denuncia', models.DateField()),
                ('acontecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alertas.Acontecimiento')),
            ],
            options={
                'verbose_name': 'Hecho',
                'verbose_name_plural': 'Hechos',
            },
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Localizacion',
                'verbose_name_plural': 'Localizacions',
            },
        ),
        migrations.CreateModel(
            name='LugarHecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('cuadra', models.CharField(max_length=30)),
                ('tipo_via', models.CharField(max_length=30)),
                ('referencia', models.CharField(max_length=30)),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alertas.Localizacion')),
            ],
            options={
                'verbose_name': 'LugarHecho',
                'verbose_name_plural': 'LugarHechos',
            },
        ),
        migrations.AddField(
            model_name='hecho',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alertas.LugarHecho'),
        ),
    ]
